### ISSUE TITLE
List a detailed bill of materials

### ISSUE THREAD

**Issue by nunoronconcouto** [josefadamcik/RoomMonitorPcb#1]
Hi!!
Can you put the list of material needed to set up your project.
I already have the PCBs from https://jlcpcb.com/
Please..

Thanks

**Comment by josefadamcik** [comment]
Hi, 
there is a rough list of parts in the article on my website: https://josef-adamcik.cz/electronics/esp8266-based-room-conditions-monitor-part-2.html

It looks like this:

-  SHT21 breakout and BH1750 breakout
-  ESP-12F module
-  TP4056 charging and protection module for 18650 Make sure you buy the one with the protection chip, some models have only the charging part and not the protection. You should never connect a Li-On cell without protection a circuit.
-  bunch of 1206 resistors (see the schematic for values)
-  a few 1206 capacitors (see the schematic for values)
-  2 THT electrolytic capacitors (10uF)
-  few pin headers (female) or you could solder the sensor boards directly to the board
-  a switch and 2 buttons
-  cell holder for 18650
-  a Li-On cell (18650)

A few items have a links to aliexpress in the [blogpost]( https://josef-adamcik.cz/electronics/esp8266-based-room-conditions-monitor-part-2.html
). I don't think including links to aliexpress is a good idea for a good BOM on github (they will stop working sooner or later).

**I don't have any more detailed BOM**. Keep in mind most of the parts were parts I already had in stock and I just measured them and picked a footprint from KiCad libraries for them. I have no part numbers or anything for most of them since they are sourced from aliexpress or salvaged from other projects.

I believe with some work it should be possible to put the BOM together based on the list above, links in the article and information from KiCad project (schematic, mapping, footprints). **Feel free to do that and create a pull-request with BOM to help others.**
